apiVersion: v1 
kind: Pod
metadata:
  name: vijay
  labels:
    name: mortene
spec:
  containers:
  - name: mortene
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
