apiVersion: v1 
kind: Pod 
metadata:
  name: jhansi
spec:
    containers:
    - name: jhansi
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports: 
        - containerPort: 80

