apiVersion: v1 
kind: Service
metadata:
  name: physics
  labels:
    name: goodnight
    type: prod
spec:
  type: NodePort
  ports:
  - targetPort: 80
    port: 80
    nodePort: 30018
  selector:
    name: goodnight
   
    
