apiVersion: v1
kind: Service
metadata:
  name: ciena
  labels:
    name: mortene
    type: prod

spec:
    type: NodePort
    ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
    selector:
       name: mortene