apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: simple-webapp
  labels:
      app: App1 
      type: frontend
  annotations:
     buildVersion: "1.34"
spec:
  replicas: 3
  selector:
     matchLabels: 
        app: App1
        type: frontend
  template:
    metadata:
       labels:
         app: App1
         type: frontend
    spec:
      containers:
      - name: simple-webapp
        image: nginx            
    